### ISSUE TITLE
Build specific version of Proton

### ISSUE THREAD

**Issue by vjrantal** [torosent/python-qpid-proton#2]
Currently building directly from git master branch. Instead, a specific release could be used.

**Comment by torosent** [comment]
You can set the `PYTHON_IMAGE_VERSION` `PROTON_VERSION` `PYTHON_DIR_VERSION` when building the image.

For example:

```docker build -t python-qpid-proton --build-arg PYTHON_IMAGE_VERSION=3.6-slim-stretch --build-arg PROTON_VERSION=0.18.1 --build-arg PYTHON__DIR_VERSION=3.6 .```
